### PR TITLE
 Catch exceptions raised during http handling #1522 

### LINKED ISSUE #1522: Catch exceptions raised during http handling
The Warp default is "Something went wrong", see https://hackage.haskell.org/package/warp-3.0.4/docs/Network-Wai-Handler-Warp.html#g:3 This message occurs e.g. in https://github.com/ontohub/ontohub/issues/1199
Instead of letting Warp handle the exception, Hets should handle it and return a `Response` with some useful error message drived from the exception.

### PR DESCRIPTION
**Pull request by tillmo**
fixes #1522

### CODE REVIEW

File: PGIP/Server.hs [hunk 1]
```diff
@@ -188,7 +194,9 @@ hetsServer opts1 = do
   putIfVerbose opts 1 $ "hets server is listening on port " ++ show port
   putIfVerbose opts 2 $ "for more information look into file: " ++ permFile
 #ifdef WARP3
-  runSettings (setPort port $ setTimeout 86400 defaultSettings) $ \ re respond -> do
+  runSettings (setOnExceptionResponse catchException $
+               setPort port $
```
Comment (cmaeder) [inline PGIP/Server.hs]: I tend to put the infix operators at the beginning of a next line (but that is matter of taste).
(Unfortunately in Scala the operator even must be at the end of a line to indicate its continuation)

Also I prefer to write "f . g $ h x" instead of "f $ g $ h x"

**Comment by cmaeder** [comment]
My checkSource.sh reports:

```
PGIP/Server.hs:168:19: trailing (2) white space
PGIP/Server.hs:169:38: trailing (1) white space
PGIP/Server.hs:170:71: trailing (1) white space
PGIP/Server.hs:198:30: trailing (1) white space
PGIP/Server.hs:171:39: put blank before ++
PGIP/Server.hs:171:41: put blank after ++
PGIP/Server.hs:276:16: Warning: Redundant $
Found:
  liftM (parseJson . B8.unpack) $ receivedRequestBody
Why not:
  liftM (parseJson . B8.unpack) receivedRequestBody
```

**Comment by cmaeder** [comment]
otherwise this patch looks ok (if it serves the purpose that I did not test) :+1:

**Comment by cmaeder** [comment]
`catchException` should be rewritten using `mkResponse` (see #1532)

I also use `textC` as content type.

**Comment by tillmo** [comment]
OK, have implemented your comments (except from that about $). Please have a look.

**Comment by cmaeder** [comment]
How about using (and/or adjusting) `textC` instead of "text/plain; charset=utf-8"?

```
PGIP/Output/Mime.hs:textC = "text/plain"
```

**Comment by tillmo** [comment]
OK, did that.

**Comment by cmaeder** [comment]
:+1:
