### PR TITLE
fix #1961

### LINKED ISSUE #1961: non-stack build fails with GUI/HTkGenericATP.hs
non-stack build is required for launchpad packages, but fails with:
```
GUI/HTkGenericATP.hs:795:17: error:
    * Could not deduce (Show sentence)
        arising from a use of `genericProveBatch'
      from the context: (Ord proofTree, Ord sentence)
        bound by the type signature for:
                   genericATPgui :: (Ord proofTree, Ord sentence) =>
                                    ATPFunctions sign sentence mor proofTree pst
                                    -> Bool
                                    -> String
                                    -> String
                                    -> Theory sign sentence proofTree
                                    -> [FreeDefMorphism sentence mor]
                                    -> proofTree
                                    -> IO [ProofStatus proofTree]
        at GUI/HTkGenericATP.hs:(309,1)-(320,33)
      Possible fix:
        add (Show sentence) to the context of
          the type signature for:
            genericATPgui :: (Ord proofTree, Ord sentence) =>
                             ATPFunctions sign sentence mor proofTree pst
                             -> Bool
                             -> String
                             -> String
                             -> Theory sign sentence proofTree
                             -> [FreeDefMorphism sentence mor]
                             -> proofTree
                             -> IO [ProofStatus proofTree]
    * In the first argument of `(>>)', namely
        `genericProveBatch
           False
           tLimit
           extOpts'
           inclProvedThs
           saveProblem_F
           afterEachProofAttempt
           (atpInsertSentence atpFun)
           (runProver atpFun)
           prName
           thName
           s
           Nothing'
      In the second argument of `($)', namely
        `genericProveBatch
           False
           tLimit
           extOpts'
           inclProvedThs
           saveProblem_F
           afterEachProofAttempt
           (atpInsertSentence atpFun)
           (runProver atpFun)
           prName
           thName
           s
           Nothing
         >> return ()'
      In a stmt of a 'do' block:
        batchProverId <- Conc.forkIO
                         $ genericProveBatch
                             False
                             tLimit
                             extOpts'
                             inclProvedThs
                             saveProblem_F
                             afterEachProofAttempt
                             (atpInsertSentence atpFun)
                             (runProver atpFun)
                             prName
                             thName
                             s
                             Nothing
                           >> return ()
```
Any hints?

### PR DESCRIPTION
**Pull request by tillmo**

### CODE REVIEW

File: GUI/HTkGenericATP.hs [hunk 1]
```diff
@@ -307,7 +307,7 @@ newOptionsFrame con updateFn isExtraOps = do
   or use a detailed GUI for proving each goal manually.
 -}
 genericATPgui
-    :: (Ord proofTree, Ord sentence)
+    :: (Ord sentence, Ord proofTree Ord sentence)
```
Comment (mcodescu) [inline GUI/HTkGenericATP.hs:310]: I think you miss a comma after `proofTree`.

**Comment by tillmo** [comment]
you are right. Still, Hets compiled, probably because `GUI/HTkGenericATP.hs ` is not used in the standard configuration.

**Review by mcodescu — APPROVED** [review]
:+1:
